FROM mcr.microsoft.com/devcontainers/php:3-8.5-trixie

# Symfony CLI installieren
RUN curl -sS https://get.symfony.com/cli/installer | bash && \
    mv /root/.symfony*/bin/symfony /usr/local/bin/symfony